name: Deploy docs

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout/@v4

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen && doxygen --version

      - name: Install Graphviz
        run: sudo apt-get install -y graphviz    

      - name: Build Documentation
        run: |
          mkdir -p build
          cd build
          cmake ..
          make doc 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html